package com.shivavashia.jobportal.entity;


import jakarta.persistence.*;

import java.util.List;

@Entity
@Table(name = "job_seeker_profile")
public class JobSeekerProfile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Automatically generated by the database
    @Column(name = "user_account_id")
    public Integer user_account_id;

    @OneToOne
    @JoinColumn(name = "user_account_id")
    @MapsId
    public Users user_id;

    @Column(name = "city")
    public String city;

    @Column(name = "country")
    public String country;

    @Column(name = "state")
    public String state;

    @Column(name = "employement_type")
    public String employement_type;

    @Column(name = "first_name")
    public String firstName;

    @Column(name = "last_name")
    public String lastName;

    @Column(nullable = true, length = 64)
    public String profile_photo;

    public String resume;

    @Column(name = "work_authorisation")
    public String work_authorisation;

    @OneToMany(targetEntity = Skills.class,cascade = CascadeType.ALL,mappedBy = "job_seeker_profile")
    public List<Skills> skills;

    public JobSeekerProfile() {
    }

    public JobSeekerProfile(Users user_id) {
        this.user_id = user_id;
    }

    public JobSeekerProfile(Integer user_account_id, Users user_id, String city, String country, String state, String employement_type, String firstName, String lastName, String profile_photo, String resume, String work_authorisation, List<Skills> skills) {
        this.user_account_id = user_account_id;
        this.user_id = user_id;
        this.city = city;
        this.country = country;
        this.state = state;
        this.employement_type = employement_type;
        this.firstName = firstName;
        this.lastName = lastName;
        this.profile_photo = profile_photo;
        this.resume = resume;
        this.work_authorisation = work_authorisation;
        this.skills = skills;
    }

    public Integer getUser_account_id() {
        return user_account_id;
    }

    public void setUser_account_id(Integer user_account_id) {
        this.user_account_id = user_account_id;
    }

    public Users getUser_id() {
        return user_id;
    }

    public void setUser_id(Users user_id) {
        this.user_id = user_id;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getEmployement_type() {
        return employement_type;
    }

    public void setEmployement_type(String employement_type) {
        this.employement_type = employement_type;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getProfile_photo() {
        return profile_photo;
    }

    public void setProfile_photo(String profile_photo) {
        this.profile_photo = profile_photo;
    }

    public String getResume() {
        return resume;
    }

    public void setResume(String resume) {
        this.resume = resume;
    }

    public String getWork_authorisation() {
        return work_authorisation;
    }

    public void setWork_authorisation(String work_authorisation) {
        this.work_authorisation = work_authorisation;
    }

    public List<Skills> getSkills() {
        return skills;
    }

    public void setSkills(List<Skills> skills) {
        this.skills = skills;
    }


    @Transient
    public String getPhotosImagePath(){
        if(profile_photo==null || user_account_id==null){
            return null;
        }
        return "/photos/candidate/" + user_account_id+"/"+profile_photo;
    }

    @Override
    public String toString() {
        return "JobSeekerProfile{" +
                "user_account_id=" + user_account_id +
                ", userId=" + user_id +
                ", city='" + city + '\'' +
                ", country='" + country + '\'' +
                ", state='" + state + '\'' +
                ", employement_type='" + employement_type + '\'' +
                ", fist_name='" + firstName + '\'' +
                ", last_name='" + lastName + '\'' +
                ", profile_photo='" + profile_photo + '\'' +
                ", resume='" + resume + '\'' +
                ", work_authorisation='" + work_authorisation + '\'' +
//                ", skills=" + skills +
                '}';
    }
}
