package com.shivavashia.jobportal.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "recruiter_profile")
public class RecruiterProfile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Automatically generated by the database
    @Column(name = "user_account_id")
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int user_account_id;
    @Column(name = "city")
    private String city;
    @Column(name = "country")
    private String country;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(nullable = true ,length = 64,name = "profile_photo")
    private String profile_photo;
    @Column(name = "state")
    private String state;
    @Column(name = "company")
    private String company;

    @OneToOne
    @JoinColumn(name = "user_account_id")
    @MapsId
    private Users user_id;

    public RecruiterProfile() {
    }

    public RecruiterProfile(Users user_id) {
        this.user_id = user_id;
    }

    public RecruiterProfile(int user_account_id, String city, String country, String firstName, String lastName, String profile_photo, String state, String company, Users user_id) {
        this.user_account_id = user_account_id;
        this.city = city;
        this.country = country;
        this.firstName = firstName;
        this.lastName = lastName;
        this.profile_photo = profile_photo;
        this.state = state;
        this.company = company;
        this.user_id = user_id;
    }

    public int getUser_account_id() {
        return user_account_id;
    }

    public void setUser_account_id(int user_account_id) {
        this.user_account_id = user_account_id;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getProfile_photo() {
        return profile_photo;
    }

    public void setProfile_photo(String profile_photo) {
        this.profile_photo = profile_photo;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public Users getUser_id() {
        return user_id;
    }

    public void setUser_id(Users user_id) {
        this.user_id = user_id;
    }

    @Transient
    public String getPhotosImagePath(){
        if(profile_photo==null){
            return null;
        }
        return "/photos/recruiter/"+user_account_id+"/"+ profile_photo;
    }


    @Override
    public String toString() {
        return "RecruiterProfile{" +
                "user_account_id=" + user_account_id +
                ", city='" + city + '\'' +
                ", country='" + country + '\'' +
                ", fist_name='" + firstName + '\'' +
                ", last_name='" + lastName + '\'' +
                ", profile_photo='" + profile_photo + '\'' +
                ", state='" + state + '\'' +
                ", comapny='" + company + '\'' +
                ", user_id=" + user_id +
                '}';
    }
}
